version: '3'
services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3002
    env_file: .env 

  
# docker-compose up --build --force-recreate
