version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-zelify
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: zelify
      POSTGRES_PASSWORD: zelify
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
   
# docker-compose up --build --force-recreate
